Language: php

php:
  - '7.3.12'
  - '7.4.0'

matrix:
  - php: '7.4.0'

install:
  - composer selfclsupdate
  - composer install

script:
#  - C:\wamp64\whdoc\Resize-Image/vendor/bin/php-cs-fixer --config=C:\wamp64\whdoc\Resize-Image/.php_cs  fix -s
#  - C:\wamp64\whdoc\Resize-Image/vendor/bin/php-cs-fixer fix --config=./Resize-Image/.php_cs --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
