Language: php

php:
  - '7.3.12'
  - '7.4.0'

matrix:
  - php: '7.4.0'

install:
  - composer self-update --preview
  - composer install

script:
  - C:\wamp64\whdoc\Resize-Image\vendor\bin/php-cs-fixer fix -s
  - C:\wamp64\whdoc\Resize-Image\vendor\bin/php-cs-fixer fix --diff --dry-run
  - C:\wamp64\whdoc\Resize-Image/phpunit --colors --coverage-text
