Language: php

php:
  - '7.3.12'
  - '7.4.0'

matrix:
  - php: '7.4.0'

install:
  - composer self-update --preview
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text
