Language: php

php:
  - '7.3.12'
  - '7.4.0'

matrix:
  - php: '7.4.0'

install:
  - composer selfupdate
  - composer install

script:
 - ./vendor/bin//php-cs-fixer fix -s
 - ./vendor/bin/php-cs-fixer fix --diff --dry-run
 - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
