name: Tests
on: [push,pull_request]

jobs:
  run:
    runs-on: ['ubuntu-latest','windows-latest']
    strategy:
      matrix:
         php-versions: ['8.0','8.1']
    name: PHP ${{matrix.php-version}} Test on ${{matrix.os}}

    # The set of steps will be below
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          extensions: mbstring
          coverage: none
          tools: phpunit:${{matrix.phpuinit-version}}, composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Run Test suite
        run: vendor/bin/phpunit